### ISSUE TITLE
mastodon verification support

### ISSUE THREAD

**Issue by mfossen** [Pinjasaur/bic#16]
Saw this come through my feed: https://fedi.tips/how-do-i-verify-my-account/

Worth adding an env var to build it in or add it in a "useful snippets" section or something to the docs for adding it yourself?

**Comment by Pinjasaur** [comment]
I don't think this would be a direct integration with bic, but rather up to the author to add to their implementation i.e. I don't think it makes sense to add built in integration e.g. via an ENV_VAR for something this niche.

That article makes it sound relatively trivial to copy & paste a one-liner HTML tag into the `<head>`. If you have trouble implementing it on your site feel free to ping or re-open.

**Comment by Pinjasaur** [comment]
I don't think this would be a direct integration with bic, but rather up to the author to add to their implementation i.e. I don't think it makes sense to add built in integration e.g. via an ENV_VAR for something this niche.

That article makes it sound relatively trivial to copy & paste a one-liner HTML tag into the <head>. If you have trouble implementing it on your site feel free to ping or re-open.
